### PR TITLE
feat: Add RSS feed

### LINKED ISSUE #195: RSS Feed
Any chance you could set [`generate_feed`](https://www.getzola.org/documentation/templates/feeds/) in your Zola config so I can subscribe to your blog?

### PR DESCRIPTION
**Pull request by dbanty**
Closes #195

### CODE REVIEW

**Comment by wezm** [comment]
Looks great. It seems like your theme automatically added the `link` tag to the `<head>` which is probably the main thing.

```html
<link rel="alternate" type="application/atom+xml" title="RSS" href="https://dylananthony.com/atom.xml">
```

That lets the feed reader auto-discover the feed from the page. The formatting of the content in the feed in [my reader of choice](https://feedbin.com/) looks off:

image

Viewing the feed in Firefox shows an XML error so looks like something is awry.

Screenshot from 2022-03-06 14-15-10

Looking at the source of the feed it seems there are two control characters in the content (U+001F), which aren't valid in XML text nodes.

Screenshot from 2022-03-06 14-17-22

Fixing that in [the post](https://github.com/dbanty/dylananthony.com/blob/48245e0c2d5e9c422c54e59e022336c19d908210/content/blog/new-year-new-website/index.md?plain=1#L33) should fix make it valid XML.

**Comment by dbanty** [comment]
Thanks for such a detailed review! No idea where those control characters came from, must have been some weird copy/paste issue at some point.

It is really strange that the reader seems to get hung up on some of the formatting. Especially since the most recent post looks okay to me?


A couple things I noticed just from clicking around which will maybe help narrow down the issue:

1. Clicking the "Extract full content" button in the top right (it's green in this screenshot) seems to _mostly_ fix the formatting for me.
2. The only issue that I see at a glance after clicking that button in that serverless languages post is that the numbered entries starting after the "Ruby" header have disappeared.3. 

Screen Shot 2022-03-05 at 9 42 17 PM

Any ideas what could be causing this?

**Comment by wezm** [comment]
I think it's fine now. It looks like Feedbin had cached the broken version and there was nothing in the feed telling it that the posts had been updated. If you subscribe to something that looks like a new URL the posts render fine: E.g.

https://dylananthony-com-git-rss-feed-dbanty.vercel.app/atom.xml?v=new

**Comment by dbanty** [comment]
Awesome, thanks! I'll go ahead and merge this then so it's available at the non-preview URL.

**Pull request merged**
